// Generated by CoffeeScript 1.10.0
(function() {
  var expect, should;

  expect = chai.expect;

  should = chai.should();

  describe("Compare Numbers - coffeescript", function() {
    var one, two;
    one = 1;
    two = 2;
    it("1 should equal 1", function() {
      return expect(one).to.equal(one);
    });
    it("2 should be greater than 1", function() {
      return two.should.be.greaterThan(one);
    });
    return it("1 should be greater than 2", function() {
      return one.should.be.greaterThan(two, "This should fail.");
    });
  });

}).call(this);
