// Generated by CoffeeScript 1.10.0
(function() {
  var lib, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  lib = {};

  lib.start = function() {
    return ReactDOM.render(React.createElement("h1", null, "Hello from React"), document.getElementById("hello"));
  };

  root.main = lib;

}).call(this);
